### ISSUE TITLE
Replace bootstrap node with AWS ASG Discovery

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-consul#21]
The bootstrap node is a hack, and is a point of failure. Ideally, here is what should be done.

Create a simple ASG with all server nodes in them. Assign a IAM role to them that has sufficient privilege to discover the nodes in the ASG, i.e.

Include awscli on the Consul nodes.

$> aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name consul-0-38 | jq '.AutoScalingGroups[0].Instances[] | .InstanceId'
$> aws ec2 describe-instances --instance i-12be111f | jq '.Reservations[0].Instances[] | .PrivateDnsName'

At this point, all Consul nodes of the ASG group can just poll for that information and attempt to auto-join whatever nodes it discovers.

This would turn the Consul nodes into 100% identical ones without a SPOF of any kind.

**Comment by gozer** [comment]
Only missing bit, is finding the name of the autoscaling group the instance is part of, easily done like this:

$> aws autoscaling describe-auto-scaling-instances --instance-ids $MY_INSTANCE_ID | jq '.AutoScalingInstances[0].AutoScalingGroupName'

**Comment by nicknovitski** [comment]
Thank you so much for noting this down in public, it put me on the right path, and today I got it working.

One thing I found out was that you don't even need jq: awscli has a --query option that lets you do very similar things.
```bash
MY_INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | sed 's/  "region" : "\(.*\)",\?/\1/')
ASG_NAME=$(/usr/local/bin/aws autoscaling describe-auto-scaling-instances --region $REGION --instance $MY_INSTANCE_ID --query 'AutoScalingInstances[0].AutoScalingGroupName' --output text)

# Block until we can find another member of the group
while [ -z "$OTHER_INSTANCE_ID" ]; do
 OTHER_INSTANCE_ID=$(/usr/local/bin/aws autoscaling describe-auto-scaling-groups --region $REGION --auto-scaling-group-name $ASG_NAME --query 'AutoScalingGroups[0].Instances[?InstanceId!=`$MY_INSTANCE_ID`].InstanceId' --output text | awk '{ print $1 }')
done
TARGET=$(/usr/local/bin/aws ec2 describe-instances --region $REGION --instance $OTHER_INSTANCE_ID --query 'Reservations[0].Instances[0].PrivateDnsName' --output text)
```

**Comment by gozer** [comment]
:clock1: 16h

**Comment by igoratencompass** [comment]
Maybe by tagging the instances in the ASG it can be even simpler:

SERVERS=$(aws --region $REGION ec2 describe-instances \  
  --filters \
  "Name=tag:Type,Values=consul" \
  "Name=tag:Role,Values=server" \
  "Name=instance-state-name,Values=running" | \
    jq -r '.Reservations[].Instances[].PrivateIpAddress' \
)

**Comment by gozer** [comment]
Working so far:

```#!/bin/bash

MY_INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | sed 's/  "region" : "\(.*\)",\?/\1/')
ASG_NAME=$(aws autoscaling describe-auto-scaling-instances --region $REGION --instance $MY_INSTANCE_ID --query 'AutoScalingInstances[0].AutoScalingGroupName' --output text)

# Block until we can find another member of the group
while [ -z "$OTHER_INSTANCE_ID" ]; do
 OTHER_INSTANCE_ID=$(aws autoscaling describe-auto-scaling-groups --region $REGION --auto-scaling-group-name $ASG_NAME --query "AutoScalingGroups[0].Instances[].InstanceId" --output text)
done

aws ec2 describe-instances --region $REGION --instance $OTHER_INSTANCE_ID --query 'Reservations[].Instances[].PrivateDnsName'
```
