### ISSUE TITLE
Design support for ACL tokens

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-consul#26]
This needs some planning on how to manage, ideally in an immutable way, the generation of client ACL tokens and their associated KV tree permissions.

**Comment by gozer** [comment]
:clock1: 8h

**Comment by gozer** [comment]
- Consul servers bootstrapped with an acl_master_token provided at launch time
 - Anonymous user kept enabled
   - Initially, all allowed
   - Eventually, locked-down
 - CI will be provided with the master token at launch time
 - CI will be responsible for provisionning ACL tokens for each project/environment/region combos
 - CI will be responsible for managing ACL rules for the deployment
 - CI will pass down the correct token when deploying via a new CF input argument
 - Nubis base images will know to look for that token and conditionnally make the Consul agent use it

consul.json:
{
  "acl_master_token" : "some-master-token",
  "acl_datacenter" : "$AWS_REGION",
  "acl_default_policy": "allow"
}

**Comment by gene1wood** [comment]
> CI will pass down the correct token when deploying via a new CF input argument

@gozer : How will the CF input value be conveyed to the ec2 instances?

**Comment by gene1wood** [comment]
Actually, I'll move my comment to #27 since #26 is closed.
