### ISSUE TITLE
Build support for ACL tokens

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-consul#27]
After #26 is sorted out, we need to implement it.

**Comment by gozer** [comment]
:clock1: 32h

**Comment by gozer** [comment]
- [ ] Consul servers bootstrapped with an acl_master_token provided at launch time
 - [ ] Anonymous user kept enabled
   - [ ] Initially, all allowed
   - [ ] Eventually, locked-down
 - [ ] CI will be provided with the master token at launch time
 - [ ] CI will be responsible for provisionning ACL tokens for each project/environment/region combos
 - [ ] CI will be responsible for managing ACL rules for the deployment
 - [ ] CI will pass down the correct token when deploying via a new CF input argument
 - [ ] Nubis base images will know to look for that token and conditionnally make the Consul agent use it

**Comment by gene1wood** [comment]
> CI will pass down the correct token when deploying via a new CF input argument

@gozer : How will the CF input value be conveyed to the ec2 instances?

**Comment by gozer** [comment]
Right now, the plan is to just use user-data for this.

**Comment by gozer** [comment]
Work will be continued in Nubisproject/nubis-ci#79
