### ISSUE TITLE
Backups for the K/V Store

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-consul#30]

**Comment by gozer** [comment]
:clock1: 4h

**Comment by limed** [comment]
This might be a handy tool https://github.com/gmr/consulate

**Comment by gozer** [comment]
There is also a tool just for this called consul-backup

**Comment by gozer** [comment]
Having looked at consul-back up close, it's immature and not good enough, IMO.

Consulate looks better to me ATM.

Of course, the ideal would be to be able to use https://github.com/hashicorp/consul-replicate, but we can't, our clusters don't know about each others.

**Comment by gozer** [comment]
Closed in  #60
