### ISSUE TITLE
Reference $aws_iam_instance_profile.consul.name instead of $var.name

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-consul#62]
https://github.com/Nubisproject/nubis-consul/blob/master/nubis/terraform/main.tf#L12
https://github.com/Nubisproject/nubis-consul/blob/master/nubis/terraform/main.tf#L60

The top 2 lines of code currently references `${var.project}` we should change that to `${aws_iam_instance_profile.consul.name}` instead

**Comment by gozer** [comment]
Ah, you caught me here. The solution isn't quite that simple, unfortunately.

The IAM instance profile is *only* created in one region, remember? So when running TF in the other region, the iam_instance_profile resource will not be created, so we need to just use it's name, so duplicating the name building logic.
